version: '2'

services:
  docktartar:
    image: gmentsik/docktartar
    privileged: false
    environment:
      CRON: "0 0 * * *"
      TIMEZONE: "Europe/Vienna"
      TAG: 'docker'
      TAR_OWNER_USERID: 0
      TAR_OWNER_GROUPID: 0
      STOP_CONTAINERS: "all"
      START_CONTAINERS: "all"
      INCREMENTAL: "true"
      SMB: "false"
      SMB_USER: ""
      SMB_PASSWORD: ""
      SMB_PATH: ""
      EMAIL_ADRESS: ""
      EMAIL_HOST_PORT: ""
      EMAIL_USER: ""
      EMAIL_PASS: ""
      EMAIL_USE_STARTTLS: ""
      EMAIL_FROM: ""
      EMAIL_FROM_ADRESS: ""
      EMAIL_SUBJECT: "Docktartar"
      EMAIL_TO: ""
      EMAIL_HOSTNAME: ""

    volumes:
    - /srv/docker:/backupSource
    - /var/backup/docker:/backupTarget
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    stdin_open: true
    network_mode: none
